
const permissionsRaw = `QUIZ_READ, QUIZ_TAKE, STAFF_ACCESS, HOMEWORK_READ, LEARNING_READ, PROVIDER_READ, QUESTION_READ, STUDENT_ACCESS, ACCOUNT_ME_READ, HOMEWORK_CREATE, HOMEWORK_DELETE, HOMEWORK_UPDATE, LEARNING_CREATE, LEARNING_UPDATE, PROVIDER_ACCESS, STAFF_CITY_READ, STAFF_DOCS_READ, STAFF_JOBS_READ, STAFF_MAIL_READ, STAFF_MAIL_SEND, STAFF_MAIL_TEST, STAFF_PAGE_READ, STAFF_ROLE_READ, STAFF_USER_READ, STUDENT_ACCESS, STAFF_TOPIC_READ, PROVIDER_ORG_READ, STAFF_CITY_CREATE, STAFF_CITY_DELETE, STAFF_CITY_UPDATE, STAFF_DOCS_UPDATE, STAFF_MAIL_CONFIG, STAFF_MAIL_STATUS, STAFF_PAGE_UPDATE, STAFF_ROLE_CREATE, STAFF_ROLE_DELETE, STAFF_ROLE_UPDATE, STAFF_USER_CREATE, STAFF_USER_DELETE, STAFF_USER_UPDATE, STUDENT_QUIZ_READ, STUDENT_QUIZ_TAKE, PROVIDER_QUIZ_READ, STAFF_ACCOUNT_READ, STAFF_JOBS_CONTROL, STAFF_SUBJECT_READ, STAFF_TOPIC_CREATE, STAFF_TOPIC_DELETE, STAFF_TOPIC_UPDATE, PROVIDER_ORG_UPDATE, PROVIDER_STAFF_READ, PROVIDER_STATS_READ, PROVIDER_TOPIC_READ, STAFF_PROVIDER_READ, STAFF_QUESTION_READ, STAFF_QUESTION_SYNC, PROVIDER_QUIZ_CREATE, PROVIDER_QUIZ_DELETE, PROVIDER_QUIZ_UPDATE, PROVIDER_REPORT_READ, STAFF_ACCOUNT_CREATE, STAFF_ACCOUNT_DELETE, STAFF_ACCOUNT_UPDATE, STAFF_SUBJECT_CREATE, STAFF_SUBJECT_DELETE, STAFF_SUBJECT_UPDATE, STUDENT_ACCOUNT_READ, PROVIDER_CONTENT_READ, PROVIDER_MEDIA_DELETE, PROVIDER_MEDIA_UPLOAD, PROVIDER_STAFF_CREATE, PROVIDER_STAFF_DELETE, PROVIDER_STAFF_UPDATE, PROVIDER_STUDENT_READ, PROVIDER_SUBJECT_READ, PROVIDER_TOPIC_CREATE, PROVIDER_TOPIC_DELETE, PROVIDER_TOPIC_UPDATE, STAFF_PROVIDER_CREATE, STAFF_PROVIDER_DELETE, STAFF_PROVIDER_UPDATE, STAFF_QUESTION_CREATE, STAFF_QUESTION_DELETE, STAFF_QUESTION_SUBMIT, STAFF_QUESTION_UPDATE, STUDENT_HOMEWORK_READ, STUDENT_LEARNING_READ, STUDENT_PROVIDER_READ, STUDENT_QUESTION_READ, PROVIDER_PROGRESS_READ, PROVIDER_QUESTION_READ, PROVIDER_REPORT_EXPORT, STAFF_QUESTION_APPROVE, STAFF_QUESTION_PUBLISH, PROVIDER_ANALYTICS_READ, PROVIDER_CONTENT_ASSIGN, PROVIDER_STUDENT_CREATE, PROVIDER_STUDENT_DELETE, PROVIDER_STUDENT_INVITE, PROVIDER_STUDENT_UPDATE, PROVIDER_SUBJECT_UPDATE, STAFF_QUESTION_GENERATE, STAFF_USER_MEDIA_DELETE, STAFF_USER_MEDIA_UPLOAD, STUDENT_HOMEWORK_CREATE, STUDENT_HOMEWORK_DELETE, STUDENT_HOMEWORK_UPDATE, STUDENT_LEARNING_CREATE, STUDENT_LEARNING_UPDATE, PROVIDER_ASSIGNMENT_READ, PROVIDER_PROGRESS_EXPORT, PROVIDER_QUESTION_CREATE, PROVIDER_QUESTION_DELETE, PROVIDER_QUESTION_SUBMIT, PROVIDER_QUESTION_UPDATE, PROVIDER_REPORT_GENERATE, PROVIDER_ACCESS_DASHBOARD, PROVIDER_APPLICATION_READ, PROVIDER_ASSIGNMENT_GRADE, PROVIDER_ORG_MEDIA_DELETE, PROVIDER_ORG_MEDIA_UPLOAD, STAFF_USER_RESET_PASSWORD, STAFF_USER_SWITCH_ACCOUNT, PROVIDER_ASSIGNMENT_CREATE, PROVIDER_ASSIGNMENT_DELETE, PROVIDER_ASSIGNMENT_SUBMIT, PROVIDER_ASSIGNMENT_UPDATE, PROVIDER_QUESTION_GENERATE, STAFF_ACCOUNT_MEDIA_DELETE, STAFF_ACCOUNT_MEDIA_UPLOAD, STAFF_SUBJECT_MEDIA_DELETE, STAFF_SUBJECT_MEDIA_UPLOAD, PROVIDER_APPLICATION_CREATE, PROVIDER_TOPIC_MEDIA_DELETE, PROVIDER_TOPIC_MEDIA_UPLOAD, STAFF_PROVIDER_MEDIA_DELETE, STAFF_PROVIDER_MEDIA_UPLOAD, STAFF_QUESTION_MEDIA_DELETE, STAFF_QUESTION_MEDIA_UPDATE, STAFF_QUESTION_MEDIA_UPLOAD, PROVIDER_SUBJECT_MEDIA_DELETE, PROVIDER_SUBJECT_MEDIA_UPLOAD, PROVIDER_QUESTION_MEDIA_DELETE, PROVIDER_QUESTION_MEDIA_UPLOAD, STAFF_QUESTION_BULK_OPERATIONS, STAFF_PROVIDER_APPLICATION_READ, STAFF_PROVIDER_APPLICATION_CREATE, STAFF_PROVIDER_APPLICATION_DELETE, STAFF_PROVIDER_APPLICATION_REJECT, STAFF_PROVIDER_APPLICATION_UPDATE, STUDENT_PROVIDER_APPLICATION_READ, STAFF_PROVIDER_APPLICATION_APPROVE, STUDENT_PROVIDER_APPLICATION_CREATE`;

const allPerms = [...new Set(permissionsRaw.split(',').map(p => p.trim()))];

const staffPerms = allPerms.filter(p => p.startsWith('STAFF_'));
const providerPerms = allPerms.filter(p => p.startsWith('PROVIDER_'));
const studentPerms = allPerms.filter(p => p.startsWith('STUDENT_') || ['QUIZ_READ', 'QUIZ_TAKE', 'LEARNING_READ', 'HOMEWORK_READ', 'LEARNING_CREATE', 'HOMEWORK_CREATE'].includes(p));

function createPermObj(perms) {
    const obj = {};
    perms.forEach(p => obj[p] = true);
    return JSON.stringify(obj).replace(/"/g, '""');
}

const roles = [
    { name: 'Provider Manager', slug: 'provider-manager', type: 'provider', isStaff: false, perms: providerPerms },
    { name: 'Provider Director', slug: 'provider-director', type: 'provider', isStaff: false, perms: providerPerms },
    { name: 'Teacher', slug: 'teacher', type: 'provider', isStaff: false, perms: providerPerms.filter(p => !p.includes('STAFF') && !p.includes('APPLICATION') && !p.includes('ORG_UPDATE')) },
    { name: 'Assistant Teacher', slug: 'assistant-teacher', type: 'provider', isStaff: false, perms: providerPerms.filter(p => !p.includes('STAFF') && !p.includes('APPLICATION') && !p.includes('ORG_UPDATE')) },
    { name: 'Staff Admin', slug: 'staff-admin', type: 'staff', isStaff: true, perms: staffPerms },
    { name: 'Staff Manager', slug: 'staff-manager', type: 'staff', isStaff: true, perms: staffPerms },
    { name: 'Content Reviewer', slug: 'content-reviewer', type: 'staff', isStaff: true, perms: staffPerms.filter(p => p.includes('QUESTION') || p.includes('TOPIC') || p.includes('SUBJECT') || p.includes('PAGE')) },
];

const generateId = () => Math.random().toString(36).substr(2, 16).toUpperCase();
const date = new Date().toISOString().replace('T', ' ').replace('Z', '+00');

console.log('id,created_at,name,slug,permissions,is_staff,for_workspace_type');
roles.forEach(r => {
    console.log(`${generateId()},${date},${r.name},${r.slug},"${createPermObj(r.perms)}",${r.isStaff},${r.type}`);
});
